/*
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link DbDSLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractDbDSLWebModule extends DefaultWebModule {

}
