/*
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DbDSLRuntimeModule extends AbstractDbDSLRuntimeModule {
}
