/*
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DbDSLStandaloneSetup extends DbDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new DbDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
