/*
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.miniproject2.dbscript.dsl.DbDSLRuntimeModule;
import org.xtext.miniproject2.dbscript.dsl.DbDSLStandaloneSetup;
import org.xtext.miniproject2.dbscript.dsl.ide.DbDSLIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class DbDSLWebSetup extends DbDSLStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DbDSLRuntimeModule(), new DbDSLIdeModule(), new DbDSLWebModule()));
	}
	
}
