/*
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class DbDSLWebModule extends AbstractDbDSLWebModule {
}
