/*
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class DbDSLIdeModule extends AbstractDbDSLIdeModule {
}
