/*
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.validation;

import org.xtext.miniproject2.dbscript.dsl.dbDSL.Table;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class DbDSLValidator extends AbstractDbDSLValidator {

	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					DbDSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
