/*
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.miniproject2.dbscript.dsl.parser.antlr.internal.InternalDbDSLParser;
import org.xtext.miniproject2.dbscript.dsl.services.DbDSLGrammarAccess;

public class DbDSLParser extends AbstractAntlrParser {

	@Inject
	private DbDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDbDSLParser createParser(XtextTokenStream stream) {
		return new InternalDbDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Database";
	}

	public DbDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DbDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
