/**
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.dbDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.AbstractType#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.AbstractType#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getAbstractType()
 * @model
 * @generated
 */
public interface AbstractType extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getAbstractType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.AbstractType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Type
   * @see #setType(Type)
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getAbstractType_Type()
   * @model
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.AbstractType#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Type
   * @see #getType()
   * @generated
   */
  void setType(Type value);

} // AbstractType
