/**
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.dbDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Column#getSourceTable <em>Source Table</em>}</li>
 *   <li>{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Column#getFkey <em>Fkey</em>}</li>
 * </ul>
 *
 * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getColumn()
 * @model
 * @generated
 */
public interface Column extends AbstractType
{
  /**
   * Returns the value of the '<em><b>Source Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Table</em>' reference.
   * @see #setSourceTable(Table)
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getColumn_SourceTable()
   * @model
   * @generated
   */
  Table getSourceTable();

  /**
   * Sets the value of the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Column#getSourceTable <em>Source Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Table</em>' reference.
   * @see #getSourceTable()
   * @generated
   */
  void setSourceTable(Table value);

  /**
   * Returns the value of the '<em><b>Fkey</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fkey</em>' attribute.
   * @see #setFkey(String)
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getColumn_Fkey()
   * @model
   * @generated
   */
  String getFkey();

  /**
   * Sets the value of the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Column#getFkey <em>Fkey</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fkey</em>' attribute.
   * @see #getFkey()
   * @generated
   */
  void setFkey(String value);

} // Column
