/**
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.dbDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLFactory
 * @model kind="package"
 * @generated
 */
public interface DbDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dbDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/miniproject2/dbscript/dsl/DbDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dbDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DbDSLPackage eINSTANCE = org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DatabaseImpl <em>Database</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DatabaseImpl
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getDatabase()
   * @generated
   */
  int DATABASE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE__NAME = 0;

  /**
   * The feature id for the '<em><b>Tables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE__TABLES = 1;

  /**
   * The feature id for the '<em><b>Inserts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE__INSERTS = 2;

  /**
   * The number of structural features of the '<em>Database</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.TableImpl
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getTable()
   * @generated
   */
  int TABLE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__COLUMNS = 1;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.AbstractTypeImpl <em>Abstract Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.AbstractTypeImpl
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getAbstractType()
   * @generated
   */
  int ABSTRACT_TYPE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_TYPE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Abstract Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.PrimaryKeyImpl <em>Primary Key</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.PrimaryKeyImpl
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getPrimaryKey()
   * @generated
   */
  int PRIMARY_KEY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_KEY__NAME = ABSTRACT_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_KEY__TYPE = ABSTRACT_TYPE__TYPE;

  /**
   * The feature id for the '<em><b>Auto Increment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_KEY__AUTO_INCREMENT = ABSTRACT_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Primary Key</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_KEY_FEATURE_COUNT = ABSTRACT_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.ColumnImpl <em>Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.ColumnImpl
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getColumn()
   * @generated
   */
  int COLUMN = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__NAME = ABSTRACT_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__TYPE = ABSTRACT_TYPE__TYPE;

  /**
   * The feature id for the '<em><b>Source Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__SOURCE_TABLE = ABSTRACT_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Fkey</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__FKEY = ABSTRACT_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_FEATURE_COUNT = ABSTRACT_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.InsertImpl <em>Insert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.InsertImpl
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getInsert()
   * @generated
   */
  int INSERT = 5;

  /**
   * The feature id for the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__TABLE = 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__VAR = 1;

  /**
   * The number of structural features of the '<em>Insert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Type <em>Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Type
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getType()
   * @generated
   */
  int TYPE = 6;


  /**
   * Returns the meta object for class '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Database <em>Database</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Database</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Database
   * @generated
   */
  EClass getDatabase();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Database#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Database#getName()
   * @see #getDatabase()
   * @generated
   */
  EAttribute getDatabase_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Database#getTables <em>Tables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tables</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Database#getTables()
   * @see #getDatabase()
   * @generated
   */
  EReference getDatabase_Tables();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Database#getInserts <em>Inserts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inserts</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Database#getInserts()
   * @see #getDatabase()
   * @generated
   */
  EReference getDatabase_Inserts();

  /**
   * Returns the meta object for class '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Table#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Table#getName()
   * @see #getTable()
   * @generated
   */
  EAttribute getTable_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Table#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Table#getColumns()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Columns();

  /**
   * Returns the meta object for class '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.AbstractType <em>Abstract Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Type</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.AbstractType
   * @generated
   */
  EClass getAbstractType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.AbstractType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.AbstractType#getName()
   * @see #getAbstractType()
   * @generated
   */
  EAttribute getAbstractType_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.AbstractType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.AbstractType#getType()
   * @see #getAbstractType()
   * @generated
   */
  EAttribute getAbstractType_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.PrimaryKey <em>Primary Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primary Key</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.PrimaryKey
   * @generated
   */
  EClass getPrimaryKey();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.PrimaryKey#getAutoIncrement <em>Auto Increment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Auto Increment</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.PrimaryKey#getAutoIncrement()
   * @see #getPrimaryKey()
   * @generated
   */
  EAttribute getPrimaryKey_AutoIncrement();

  /**
   * Returns the meta object for class '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Column <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Column
   * @generated
   */
  EClass getColumn();

  /**
   * Returns the meta object for the reference '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Column#getSourceTable <em>Source Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source Table</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Column#getSourceTable()
   * @see #getColumn()
   * @generated
   */
  EReference getColumn_SourceTable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Column#getFkey <em>Fkey</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fkey</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Column#getFkey()
   * @see #getColumn()
   * @generated
   */
  EAttribute getColumn_Fkey();

  /**
   * Returns the meta object for class '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Insert
   * @generated
   */
  EClass getInsert();

  /**
   * Returns the meta object for the reference '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Insert#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Table</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Insert#getTable()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Table();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Insert#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Var</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Insert#getVar()
   * @see #getInsert()
   * @generated
   */
  EAttribute getInsert_Var();

  /**
   * Returns the meta object for enum '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type</em>'.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Type
   * @generated
   */
  EEnum getType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DbDSLFactory getDbDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DatabaseImpl <em>Database</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DatabaseImpl
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getDatabase()
     * @generated
     */
    EClass DATABASE = eINSTANCE.getDatabase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATABASE__NAME = eINSTANCE.getDatabase_Name();

    /**
     * The meta object literal for the '<em><b>Tables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATABASE__TABLES = eINSTANCE.getDatabase_Tables();

    /**
     * The meta object literal for the '<em><b>Inserts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATABASE__INSERTS = eINSTANCE.getDatabase_Inserts();

    /**
     * The meta object literal for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.TableImpl
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE__NAME = eINSTANCE.getTable_Name();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__COLUMNS = eINSTANCE.getTable_Columns();

    /**
     * The meta object literal for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.AbstractTypeImpl <em>Abstract Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.AbstractTypeImpl
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getAbstractType()
     * @generated
     */
    EClass ABSTRACT_TYPE = eINSTANCE.getAbstractType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_TYPE__NAME = eINSTANCE.getAbstractType_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_TYPE__TYPE = eINSTANCE.getAbstractType_Type();

    /**
     * The meta object literal for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.PrimaryKeyImpl <em>Primary Key</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.PrimaryKeyImpl
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getPrimaryKey()
     * @generated
     */
    EClass PRIMARY_KEY = eINSTANCE.getPrimaryKey();

    /**
     * The meta object literal for the '<em><b>Auto Increment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIMARY_KEY__AUTO_INCREMENT = eINSTANCE.getPrimaryKey_AutoIncrement();

    /**
     * The meta object literal for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.ColumnImpl <em>Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.ColumnImpl
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getColumn()
     * @generated
     */
    EClass COLUMN = eINSTANCE.getColumn();

    /**
     * The meta object literal for the '<em><b>Source Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN__SOURCE_TABLE = eINSTANCE.getColumn_SourceTable();

    /**
     * The meta object literal for the '<em><b>Fkey</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN__FKEY = eINSTANCE.getColumn_Fkey();

    /**
     * The meta object literal for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.InsertImpl <em>Insert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.InsertImpl
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getInsert()
     * @generated
     */
    EClass INSERT = eINSTANCE.getInsert();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__TABLE = eINSTANCE.getInsert_Table();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT__VAR = eINSTANCE.getInsert_Var();

    /**
     * The meta object literal for the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Type <em>Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Type
     * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.impl.DbDSLPackageImpl#getType()
     * @generated
     */
    EEnum TYPE = eINSTANCE.getType();

  }

} //DbDSLPackage
