/**
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.dbDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Insert#getTable <em>Table</em>}</li>
 *   <li>{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Insert#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getInsert()
 * @model
 * @generated
 */
public interface Insert extends EObject
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference.
   * @see #setTable(Table)
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getInsert_Table()
   * @model
   * @generated
   */
  Table getTable();

  /**
   * Sets the value of the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Insert#getTable <em>Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' reference.
   * @see #getTable()
   * @generated
   */
  void setTable(Table value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute list.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getInsert_Var()
   * @model unique="false"
   * @generated
   */
  EList<String> getVar();

} // Insert
