/**
 * generated by Xtext 2.23.0
 */
package org.xtext.miniproject2.dbscript.dsl.dbDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Key</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.PrimaryKey#getAutoIncrement <em>Auto Increment</em>}</li>
 * </ul>
 *
 * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getPrimaryKey()
 * @model
 * @generated
 */
public interface PrimaryKey extends AbstractType
{
  /**
   * Returns the value of the '<em><b>Auto Increment</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.miniproject2.dbscript.dsl.dbDSL.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Auto Increment</em>' attribute.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Type
   * @see #setAutoIncrement(Type)
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.DbDSLPackage#getPrimaryKey_AutoIncrement()
   * @model
   * @generated
   */
  Type getAutoIncrement();

  /**
   * Sets the value of the '{@link org.xtext.miniproject2.dbscript.dsl.dbDSL.PrimaryKey#getAutoIncrement <em>Auto Increment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Auto Increment</em>' attribute.
   * @see org.xtext.miniproject2.dbscript.dsl.dbDSL.Type
   * @see #getAutoIncrement()
   * @generated
   */
  void setAutoIncrement(Type value);

} // PrimaryKey
